services:
  ollama:
    build:
      args:
        OLLAMA_BASE: ollama/ollama:rocm
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - "${VIDEO_GID:-video}"
      - "${RENDER_GID:-render}"
    environment:
      - HSA_OVERRIDE_GFX_VERSION

  llamacpp:
    image: ghcr.io/ggml-org/llama.cpp:server-vulkan
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - "${VIDEO_GID:-video}"
      - "${RENDER_GID:-render}"
    environment:
      LLAMA_ARG_N_GPU_LAYERS: "999"

  tts:
    build:
      args:
        TORCH_INDEX: https://download.pytorch.org/whl/rocm6.2
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - "${VIDEO_GID:-video}"
      - "${RENDER_GID:-render}"
    environment:
      - HSA_OVERRIDE_GFX_VERSION
