CREATE TABLE IF NOT EXISTS user_bans (
  user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  until INTEGER NOT NULL DEFAULT 0,
  strikes INTEGER NOT NULL DEFAULT 0,
  last_ban INTEGER NOT NULL DEFAULT 0,
  reason TEXT
);
INSERT INTO schema_version(v) VALUES (9);
